version: "3"

services:
   backend:
      build: ./php
      depends_on:
      - mysql
      ports:
      - 8001:80
   frontend:
      build: ./frontend
      depends_on:
      - backend
      volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
      - 8002:80
