version: "3"

services:
   backend:
      build: ./backend
      ports:
      - 8004:80
   frontend:
      build: frontend
      depends_on:
      - backend
      volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/site:/usr/share/nginx/html
      ports:
      - 80:80
