version: "3"

services:
   backend:
      build: ./php
   frontend:
      build: frontend
      depends_on:
      - backend
      volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/public_html:/usr/share/nginx/html
      ports:
      - 8080:80
